#!/bin/bash

# Got this from firafont repo. Pretty cool font to use with gruvebox theme

mkdir -p "$HOME/src"
cd "$HOME/src"
git clone git@github.com:mozilla/Fira.git
sudo cp "$HOME"/src/Fira/ttf/* /usr/share/fonts/truetype/fira
rm -rf "$HOME/src"
