#!/bin/sh

sudo dnf update
sudo dnf install git \
    vim-enhanced \
    ncurses-devel \
    xclip \
    lynx \
    tmux \
    python3.8 \
    python3.7 \
    python3.6 \
    python3.5 \

# ycm deps
sudo dnf install cmake \
    gcc-c++ \
    make \
    python3-devel \
    mono-devel \
    golang \
    nodejs \
    npm

git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
cd ~/.vim/bundle/YouCompleteMe || exit
python3 install.py --all

chmod +x "$PWD/configure"
/bin/bash "$PWD/configure"
