#!/bin/bash

APIKEY=API_KEY
DOMAIN=DOMAIN_NAME
FROM="YOU <mailgun@$DOMAIN>"
SUBJECT="Email Subject - $(date)"

TARGET=target@email.com

MESSAGE=$(cat)

curl -s --user "api:$APIKEY" \
    https://api.mailgun.net/v3/$DOMAIN/messages \
    -F from="$FROM" \
    -F to=$TARGET \
    -F subject="$SUBJECT" \
    -F text="$MESSAGE"
