#!/bin/bash

if [ $# -eq 0 ]; then
      echo "must provide remote name to ssh into"
fi

COMMANDS=$HOME/Github/devenv/dotfiles/macos/scripts

while  :
do
    report=$(ssh "$1" "bash -s" < "$COMMANDS"/sysinfo)
    echo "$report" > /tmp/out.html 2>&1
    sleep 10
done
