#!/bin/bash

sudo apt-get install dconf-cli uuid-runtime

# clone the repo into "$HOME/src/gogh"
mkdir -p "$HOME/src"
cd "$HOME/src"
git clone https://github.com/Mayccoll/Gogh.git gogh
cd gogh/themes

# necessary on ubuntu
export TERMINAL=gnome-terminal

# install themes
./gruvbox-dark.sh

# remove cloned repo
rm -rf "$HOME/src"
