#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "must provide a project name"
    exit
fi

git init
git add -A
git commit -m "initial commit"
git remote add origin git@gitlab.com:_northernsage/"$1".git
git push --set-upstream origin master
