#!/bin/bash

sudo apt install libncurses5-dev libgtk2.0-dev libatk1.0-dev \
libcairo2-dev libx11-dev libxpm-dev libxt-dev python2-dev \
python3-dev ruby-dev lua5.2 liblua5.2-dev libperl-dev git

sudo apt remove vim vim-runtime gvim

sudo cp -r /usr/include/lua5.1/* /usr/include/lua5.1/include/
sudo ln -s /usr/lib/x86_64-linux-gnu/liblua5.1.so /usr/local/lib/liblua.so

cd $HOME
git clone https://github.com/vim/vim.git
cd vim

# enable/disable prefered confi here

./configure --with-features=huge \
            --enable-multibyte \
            --enable-rubyinterp=yes \
            --enable-pythoninterp=yes \
            --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu/ \
            --enable-python3interp=yes \
            --with-python3-config-dir=$(python3-config --configdir) \
            --disable-gui \
            --disable-netbeans \
            --enable-perlinterp=yes \
            --enable-cscope \
            --enable-luainterp=yes \
            --with-lua-prefix=/usr/include/lua5.1 \
            ----enable-largefile \
            --prefix=/usr/local

make reconfig
make VIMRUNTIMEDIR=/usr/local/share/vim/vim9
sudo make install

echo "you should see correct vim version bellow"
vim --version
