#!/bin/bash

cd $HOME/repos/github.com/northernSage/ssh
git add -A
git commit -m "backup $(date)"
git push

cd $HOME/repos/github.com/northernSage/dotfiles
git add -A
git commit -m "backup $(date)"
git push

echo "Done!"
