#!/bin/bash

DSTRMT=backup
DSTLOCAL=/run/media/gfvante/backup

ENCRYPTED=$(crypt "$1")
chmod 700 "$ENCRYPTED"
rsync -aLvz "$ENCRYPTED" dobox:~/$DSTRMT
rsync -aLvz "$ENCRYPTED" $DSTLOCAL
rm "$ENCRYPTED"
