#!/bin/bash

# Youtube music player (ytp) script since I was getting tired of alt+tabbing off
# my terminal every time I wanted to change music. It works on top of mpv and
# makes curl requests to youtube API to get video IDs based on a search keyword.
# why? so we can play stuff without leaving vim of course :D

MAX=10
YT_API_URL=https://youtube.googleapis.com/youtube/v3
YT_BASE_VIDEO_URL=https://www.youtube.com/watch?v=

# because noone said things can't be pretty
declare -r red=$'\033[38;2;255;50;50m'
declare -r reset=$'\033[0m'

# check if all dependencies are installed
if [ ! -x "$(command -v mpv)" ]; then
    echo $red"It doesn't look like mpv is installed."$reset
    exit
fi
if [ ! -x "$(command -v youtube-dl)" ]; then
    echo $red"It doesn't look like youtube-dl is installed."$reset
fi
if [ -z $YT_API_KEY ]; then
    echo $red"You need to set YT_API_KEY to your api key."$reset
fi

if [ "$1" = "-s" ]; then
    pkill mpv
    exit
fi

SCAPED_SEARCH_TERM="${1// /%20}"

RESULT=$(curl "$YT_API_URL/search?part=snippet&maxResults=$MAX&q=$SCAPED_SEARCH_TERM&key=$YT_API_KEY&regionCode=GB&type=video" 2>/dev/null --header 'Accept: application/json' --compressed | grep -e "videoId" -e "title")


VIDEO_IDS=()
VIDEO_TITLES=()

IS_ID=true
while IFS= read -r line; do
    # xargs to trim off extra spaces and remove quotes
    TRIMMED_LINE=$(echo "$line" | xargs)
    # we alternate since video lines will follow order:
    #   iteration 1: video id
    #   iteration 2: video title
    #   repeat 1, 2, 1, 2, ...
    if [ "$IS_ID" = true ]; then
        IFS=' '; FIELDS=($TRIMMED_LINE); IFS=$'\n'
        VIDEO_IDS+=("${FIELDS[1]}")
        IS_ID=false
    else
        # titles have spaces, so split on ":" instead
        IFS=':'; FIELDS=($TRIMMED_LINE); IFS=$'\n'
        VIDEO_TITLES+=("$(echo ${FIELDS[1]} | xargs)")
        IS_ID=true
    fi
done <<< "$RESULT"

# show list of videos
for i in "${!VIDEO_TITLES[@]}"; do
    printf "%s. %s\n" "$i" "${VIDEO_TITLES[$i]}"
done

read -p "Pick one to play: " IDX_CHOICE
mpv --no-video "${YT_BASE_VIDEO_URL}${VIDEO_IDS[$IDX_CHOICE]}" 1>/dev/null 2>&1 &
