#!/bin/bash

declare -r reset=$'\033[0m'
declare -r cyan=$'\033[38;2;0;255;255m'

if [ -z "$(which lynx)" ]; then
  echo lynx is not installed.
  exit 1
fi

mkdir ~/.config/ 2>/dev/null
rm -rf ~/.config/lynx 2>/dev/null
ln -s "$PWD" "$HOME/.config/lynx"
ls -l ~/.config/lynx

echo $cyan"Now just put lynx into your PATH"$reset
